### ISSUE TITLE
swirl課程目錄位置

### ISSUE THREAD

**Issue by wush978** [ntuaha/DSC_R_ETL_SWIRL_2015#1]
麻煩把swirl課程拉到單獨的一個資料夾（否則README.md會跑到lession之中）

為了所有課程名稱的一致性，請建立一個名為"DSC2015"的資料夾，並且把ETL複製進去並重新取名：`R_ETL`

例如：

``` sh
mkdir DSC2015
mv ETL DSC2015/R_ETL
```

謝謝了

**Comment by ntuaha** [comment]
已經更新成功囉
